### ISSUE TITLE
Bug report during execuating s4/train.sh "train.sh: line 5: spring.submit: command not found"

### ISSUE THREAD

**Issue by DemonsHunter** [OpenNLPLab/AVSBench#7]
Encounter a bug during execuating s4/train.sh

 '''train.sh: line 5: spring.submit: command not found'''

I can not find any related solutions on the Internet. Does anyone have the same question?

**Comment by jasongief** [comment]
Hi, you may try to directly use this command:
``CUDA_VISIBLE_DEVICES=0 python train.py ... ...``

**Comment by DemonsHunter** [comment]
Thank you for your suggestion, it can directly run, but it shows following problem message:
```
Traceback (most recent call last):
  File "train.py", line 176, in <module>
    output, visual_map_list, a_fea_list = model(imgs, audio_feature) # [bs*5, 1, 224, 224]
  File "/root/miniconda3/envs/avs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/avs/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/root/miniconda3/envs/avs/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/root/miniconda3/envs/avs/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/root/miniconda3/envs/avs/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/avs/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/root/miniconda3/envs/avs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yhling/avs/avs_scripts/avs_s4/model/ResNet_AVSModel.py", line 245, in forward
    conv_feat_va, a_fea = self.tpavi_va(feature_map_list[i], audio_feature, stage=i)
  File "/home/yhling/avs/avs_scripts/avs_s4/model/ResNet_AVSModel.py", line 204, in tpavi_va
    audio = audio.view(-1, 5, audio.shape[-1]) # [B, T, 128]
RuntimeError: shape '[-1, 5, 128]' is invalid for input of size 384
```
I **do not change** any part of the released code, so I am kinda of puzzeled about this.

**Comment by jasongief** [comment]
Please refer to [issue #6](https://github.com/OpenNLPLab/AVSBench/issues/6).
