### ISSUE TITLE
Bug report 'from torchvggish import vggish'

### ISSUE THREAD

**Issue by DemonsHunter** [OpenNLPLab/AVSBench#8]
when I cd to 'avs_scripts/avs_s4' and run 'from torchvggish import vggish'

it reports following error message:

> 

```
Traceback (most recent call last):
  File "/root/miniconda3/envs/avs/lib/python3.7/site-packages/soundfile.py", line 151, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/avs/lib/python3.7/site-packages/soundfile.py", line 178, in <module>
    _snd = _ffi.dlopen(_os.path.join(_path, '_soundfile_data', _packaged_libname))
OSError: cannot load library '/root/miniconda3/envs/avs/lib/python3.7/site-packages/_soundfile_data/libsndfile.so': /root/miniconda3/envs/avs/lib/python3.7/site-packages/_soundfile_data/libsndfile.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yhling/avs/avs_scripts/avs_s4/torchvggish/vggish.py", line 6, in <module>
    from . import vggish_input, vggish_params
  File "/home/yhling/avs/avs_scripts/avs_s4/torchvggish/vggish_input.py", line 27, in <module>
    import soundfile as sf
  File "/root/miniconda3/envs/avs/lib/python3.7/site-packages/soundfile.py", line 189, in <module>
    _snd = _ffi.dlopen(_libname)
OSError: cannot load library 'libsndfile.so': libsndfile.so: cannot open shared object file: No such file or directory
```

I wonder if there is something I missed. Thank you for your help in advance~

**Comment by DemonsHunter** [comment]
I tried 2 things and finally deal with it:
1. 
`pip install librosa==0.6.0 numba==0.48.0`
2.
`yum install libsndfile`

this works for me
